resolutions:
  - "100kb"

# The parent folder up to the cell line folder (this should contain all the folders: 100kb, 50kb, etc...)
parent_folder: "../stuff/example_data/GM12878/"
output_folder: "../results/zscore/GM12878/"